---
- name: 1. System Preparation for Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Ensure iptables can see bridged traffic
      ansible.builtin.copy:
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        dest: /etc/sysctl.d/k8s.conf
        mode: '0644'

    - name: Apply sysctl settings
      ansible.builtin.command: sysctl --system

    - name: Disable swap permanently
      ansible.builtin.shell: |
        swapoff -a
        sed -i '/swap/s/^/#/' /etc/fstab

    - name: Load required kernel modules
      ansible.builtin.copy:
        content: |
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf
        mode: '0644'

    - name: Ensure kernel modules are loaded
      ansible.builtin.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter
